### ISSUE TITLE
Хэсперы для viewport и scissor

### ISSUE THREAD

**Issue by AlexandrShcherbakov** [msu-graphics-group/vk_graphics_basic#1]
https://github.com/msu-graphics-group/vk_graphics_basic/blob/47ef156a8a02d6502c7f7347752f3988a2ea70eb/src/render/simple_render.cpp#L210

Возможно стоит сделать хэлперы для выставления этих структур.

**Comment by v-san** [comment]
Добавил хелперы для создания и выставления дефолтных viewport и scissor из разрешения:
vk_utils.h:
  void setDefaultViewport(VkCommandBuffer a_cmdBuff, float a_width, float a_height);
  void setDefaultScissor(VkCommandBuffer a_cmdBuff, uint32_t a_width, uint32_t a_height);

Кому нужно будет нужно что-то более хитрое (менять оффсеты, диапазон для глубины, несколько вьюпортов/ножниц и т.д.), может это сделать руками - вряд ли хэлпер сможет ощутимо упростить/уменьшить код в таких случаях.
