### ISSUE TITLE
Проверка работы демо с включенным ImGui на видеокартах AMD.

### ISSUE THREAD

**Issue by antiHiXY** [msu-graphics-group/vk_graphics_basic#23]
При попытке запуска с включенным ImGui возникает ошибка такого формата.
![image](https://user-images.githubusercontent.com/14835489/158189589-c73fb63d-dd73-444e-a7a0-cf229087c278.png)
Еще была вот такого рода ошибка, если я пытался полностью отключить ImGui из демо с ним.
![image](https://user-images.githubusercontent.com/14835489/158189856-b3430158-bb56-4322-b8f3-0ec91e290a49.png)

**Comment by v-san** [comment]
Ошибка исправлена. 
Также теперь при назначении
```
showGUI = false;
```
imGUI не будет инициализирован вообще.
