### ISSUE TITLE
Выкинуть LiteMath и перейти на glm

### ISSUE THREAD

**Issue by Mrkol** [msu-graphics-group/vk_graphics_basic#24]
Не вижу ни одной разумной причины использовать неполную самописную имплементацию, когда есть проверенная временем, полноценная библиотека. Отсутствие матриц 3х3, функций для работы с матрицами (вычисления собственных значений), отсутствие унарного оператора - для объектов, неэффективные имплементации, не использующие SIMD -- лишь несколько из сотен недостатков LiteMath, исправить которые за разумные сроки не возможно (и не нужно).

**Comment by FROL256** [comment]
На счёт матриц 3x3 -- их можно добавить, но я бы не стал. Дело в том, что при переносе в структур с матрицами 3x3, как и на самом деле структур содержащих float3/vec3 можно напороться на очень неприятные особенности выравнивания в GLSL. Поэтому лучше используйте матрицы 4x4.
