### ISSUE TITLE
Перезагрузка шейдеров

### ISSUE THREAD

**Issue by AlexandrShcherbakov** [msu-graphics-group/vk_graphics_basic#4]
Нужна возможность перезагружать шйдеры налету. Это сильно ускорит разработку.

**Comment by v-san** [comment]
Можешь уточнить? Типа сделать возможность в работающей программе через тот же imgui менять/перезагружать используемые шейдеры (ну и соответственно автоматически пересоздавать все нужные объекты)?

**Comment by AlexandrShcherbakov** [comment]
Через ImGUI или какой-нибудь hotkey. Суть в том, что мы пересоздаём автоматически все пайплайны, и прочее.

**Comment by v-san** [comment]
Сделал простую перекомпиляцию шейдеров и пересоздание пайплайнов (на кнопку 'B', в гуи есть подсказка). Реализация простая - через запуск внешнего скрипта. Биндинги, in/out в шейдерах никак не анализируются, поэтому менять их сейчас при перезагрузке нельзя.
Можно ещё подцепить glslang как библиотеку, но не хочется переусложнять базовый сэмпл.
