### ISSUE TITLE
Надо сделать Raytracing опциональным

### ISSUE THREAD

**Issue by AlexandrShcherbakov** [msu-graphics-group/vk_graphics_basic#7]
Трассировка нужна далеко не каждый раз и лучше сделать её опциональной и написать в ReadMe как включать/исключать RT из сборки.

**Comment by v-san** [comment]
Raytracing и так опциональный - хэлперы для него расположены в vkutils/ray_tracing и этот сэмпл их не подключает и не собирает. Хэлперы сейчас используются так, что пользователь просто добавляет те хэлперы, которые нужны в CMake-конфигурацию проекта и они компилируются вместе с ним. Соответственно то, что не используется не будет и собираться.  
Я слегка реорагнизовал исходники по разными переменным в CMakeLists, чтобы отделить хелперы и сделать этот момент более понятным.
Среди других вариантов:
1. Вынести хэлперы для трассировки в отдельный репозиторий. Но там всего 4 мелких файла и кажется, что не смысла так дробить исходники.
2. Сделать скрипт для частичного клонирования репозитория хэлперов (sparse checkout вроде в гите).
